server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: pos-gateway
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: carts-service
          uri: lb://carts-service
          predicates:
            - Path=/api/carts/**